### ISSUE TITLE
C4 diagrsms not rendered

### ISSUE THREAD

**Issue by Volland** [agirorn/plantuml#11]
const plantuml = require('plantuml');
const tslab = require("tslab");
const svg = await plantuml(`
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person_Ext(issuer, "Issuer")
Boundary(b1,"Verification") {
Person(holder, "Holder", $sprite="person2")
Person(verifier, "Verifier")
}

Rel_L(issuer, holder, "issue VC", "Request for offer")
Rel(holder, issuer, "claim", "Response for offer")
Rel_R(verifier, holder, "ask for VCs", "Request for sharing")
Rel(holder, verifier, "issue signed VP", "VP", $sprite = "&envelope-closed")

@enduml
`);
tslab.display.svg(svg)

**Comment by agirorn** [comment]
Thanks for the feedback. 

The module was using an older version of PlanUML and has been updated to use version [1.2022.7](https://plantuml.com/download) now and should support the c4 diagrams in version 0.0.2.

I hope this solves your issues with the module.
